// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xojhynyrpsyaghkgrsud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvamh5bnlycHN5YWdoa2dyc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzg3MTEsImV4cCI6MjA2OTk1NDcxMX0.ekcAFzJ-IJH09Cu5Kzy55ZuKszFCUbYEDoV4GfvQovY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});